### ISSUE TITLE
Check `lite` theme

### ISSUE THREAD

**Issue by manuel-cid** [OntimizeWeb/ontimize-web-ngx-theming#32]
Check the following issues in the `lite` theme:
- [ ] Button icons should be smaller with lite than without it.
- [ ] Unify table and form buttons (table buttons have rounded border and form buttons doesn't)

**Comment by daniel-grana** [comment]
Solved with the [issue](https://github.com/OntimizeWeb/ontimize-web-ngx/issues/623)
